#коронер
- type: entity
  id: LockerCoroner
  parent: LockerBase
  name: coroner locker
  description: le morgue.
  components:
  - type: Sprite
    sprite: Imperial/Roles/Medical/Coroner/closet.rsi
  - type: Appearance
  - type: EntityStorageVisuals
    stateBaseClosed: coroner
    stateDoorOpen: coroner_open
    stateDoorClosed: coroner_door
  - type: AccessReader
    access: [ [ "Medical" ] ]

- type: entity #патологоанатом
  id: LockerCoronerFilled
  suffix: Filled
  parent: LockerCoroner
  components:
  - type: StorageFill
    contents:
      - id: Brutepack
        amount: 2
      - id: Ointment
        amount: 2
      - id: Bloodpack
        amount: 2
      - id: Scalpel
      - id: HandLabeler
      - id: ClothingHandsGlovesNitrile
      - id: BoxFolderBlue
      - id: Dropper
      - id: BoxSyringe
      - id: BoxBodyBag
      - id: Paper
        amount: 10
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.8
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: RubberStampCoroner
