- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  psychosisGainResist: 0.7 # psychosis
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 7200 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 7200 #Imperial role timers
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 28800 #Imperial role timers
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction
  #- skillPharmaceuticals
  - skillPharmacology
  - skillSurgery
  - skillMedicalEquipment
  - skillNeuroSurgery

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
  storage:
    back:
      - BoxSurvivalMedical

- type: entity
  id: SpawnPointSeniorPhysician
  parent: SpawnPointJobBase
  name: seniorphysician
  components:
  - type: SpawnPoint
    job_id: SeniorPhysician
  - type: Sprite
    layers:
      - state: green
      - state: seniorphysician
