- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800 #Imperial role timers
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction
  - skillPiloting
  - skillShooting

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorOfficer
    back: ClothingBackpackSecurityFilledSeniorOfficer # Imperial @keeyn
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatSeniorOfficerBeret #Imperial_edit Beret lives matter @keeyn
    outerClothing: ClothingOuterArmorBasic
    id: SeniorOfficerPDA
    gloves: ClothingHandsGlovesCombat # Imperial @keeyn
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltMilitaryWebbingSeniorOfficerFilled # Imperial @keeyn
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtSeniorOfficer
  satchel: ClothingBackpackSecurityFilledSeniorOfficer # Imperial @keeyn
  duffelbag: ClothingBackpackDuffelSecurityFilledSeniorOfficer # Imperial @keeyn

- type: entity
  id: SpawnPointSeniorOfficer
  parent: SpawnPointJobBase
  name: seniorofficer
  components:
  - type: SpawnPoint
    job_id: SeniorOfficer
  - type: Sprite
    layers:
      - state: green
      - state: seniorofficer
